default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: find_my_coffee_api_development
  host: ec2-54-204-99-176.compute-1.amazonaws.com
  username: postgres
  host: localhost
  
test:
  <<: *default
  database: find_my_coffee_api_test
  username: postgres
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL_PROD'] %>
  host: ec2-54-204-99-176.compute-1.amazonaws.com
  database: dbplnaf0mb9c61
  username: hanvbydhfpcigl
