default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: find_my_coffee_api_development

  
test:
  <<: *default
  database: find_my_coffee_api_test

production:
  <<: *default
  host: ec2-54-204-99-176.compute-1.amazonaws.com
  database: dbplnaf0mb9c61
  username: hanvbydhfpcigl
  password: <%= ENV['FIND_MY_COFFEE_API_DATABASE_PASSWORD'] %>
